/* ================================================================== */
/* THE SCENARIO                                                       */
/*                                                                    */
/* Where you are dropping. One object, owned by the shell, read by    */
/* every surface that has an opinion about context.                   */
/*                                                                    */
/* It was called the brief until 21 August 2026. The curator's word    */
/* is scenario and it is the better one: a brief is a document you     */
/* are handed, and this is the situation you are walking into. The     */
/* word had also been leaking into on screen copy without ever being   */
/* defined anywhere, which is why nobody could tell what it meant.     */
/*                                                                    */
/* Faction is first and it is deliberately not a filter. You have     */
/* already chosen a front before you open this tool, the mission and  */
/* biome lists differ per front, and there is no useful reading of    */
/* "how good is this against Terminids" while you are mid Illuminate  */
/* run. So it gates rather than narrows: no faction, no table.        */
/*                                                                    */
/* This starts with faction alone. Biome, weather, planet, mission    */
/* and difficulty join it, which is why it is an object from the      */
/* start rather than a string that has to be widened later.           */
/* ================================================================== */

import { useState, useCallback, useEffect } from "react";
import { SETTINGS, readSetting, writeSetting, readDoc, writeDoc } from "./storage.js";
import PLANETS from "../data/planets.json";
import MISSIONS from "../data/missions.json";

export const FACTION_IDS = ["bots", "bugs", "squids"];

/* Null means not chosen, which is a real state rather than a missing  */
/* value: it is what puts the chooser on screen instead of the table.  */
/*                                                                     */
/* Faction is required. The environment is not: you can browse a front */
/* without having picked where you are dropping, and most sessions     */
/* will. Picking a planet fills biome and hazards in one move, and     */
/* both stay editable afterwards, so the picker is a shortcut rather   */
/* than a mode.                                                        */
export const EMPTY_SCENARIO = { faction: null, planet: null, biome: null, hazards: [], mission: null, difficulty: 0, squad: 0 };

/* Zero is not a difficulty, it is the absence of one, and the slider    */
/* spells it that way already. Kept as 0 rather than null so the control */
/* and the value agree without a translation step between them.          */
export const NO_DIFFICULTY = 0;

/* Same convention for how many of you are dropping. Zero is not a squad
   of nobody, it is not having said. Solo and a full four are different
   games at the same difficulty: alone, a loud gun brings the whole base
   down on you and there is nobody to hold the line while you run. */
export const NO_SQUAD = 0;

const isFaction = (v) => FACTION_IDS.includes(v);

/* The planet table, shipped rather than fetched. Biome and permanent   */
/* hazards are static facts about a planet, so this needs no network at */
/* runtime. Generated by scripts/fetch-wiki.mjs from the helldivers-2   */
/* community dataset, MIT licensed.                                     */
export const planets = PLANETS.planets;
export const biomeInfo = PLANETS.biomes;
export const hazardInfo = PLANETS.hazards;

export const planetByName = new Map(planets.map((p) => [p.name, p]));
export const biomeName = (slug) => (biomeInfo[slug] ? biomeInfo[slug].name : slug);
export const hazardName = (slug) => (hazardInfo[slug] ? hazardInfo[slug].name : slug);
/* The description is the useful half. "Ion storms intermittently       */
/* disable Stratagems" is a rule; "Ion Storms" is a label.              */
export const hazardEffect = (slug) => (hazardInfo[slug] ? hazardInfo[slug].description : "");

/* Two entries in the hazard table are the absence of one. Every planet
   with nothing special going on lists normal_temp, so counting it made
   an ordinary planet read as hazardous. One definition, used by every
   surface that lists what a planet does to you. The scenario keeps them,
   since nothing reads them and a planet's own list is the fact. */
export const QUIET_HAZARDS = new Set(["none", "normal_temp"]);
export const loudHazards = (list) => (list || []).filter((h) => !QUIET_HAZARDS.has(h));

/* Missions are chosen by the name the game uses. The traits underneath   */
/* are what a scoring rule keys on, because "Retrieve Valuable Data" is   */
/* the right thing to put in front of a person and "carry" is the right   */
/* thing to put in front of a rule.                                       */
export const missions = MISSIONS.missions;
export const missionTraits = MISSIONS.traits;
export const missionByName = new Map(missions.map((m) => [m.name, m]));
export const missionsFor = (faction) =>
  missions.filter((m) => !faction || m.factions.includes(faction));
export const traitsOf = (name) => {
  const m = missionByName.get(name);
  return m ? m.traits : [];
};

/* ------------------------------------------------------------------ */
/* A scenario from somewhere else                                      */
/*                                                                     */
/* In a party the host's scenario arrives over the wire, and the       */
/* server has no opinion about what one is. So it is cleaned against   */
/* this browser's own tables, field by field, the same bounds the      */
/* storage read below applies: a planet or mission that does not       */
/* resolve is dropped rather than carried, and no front means nothing  */
/* usable arrived.                                                     */
/* ------------------------------------------------------------------ */

const inRange = (v, lo, hi) => Number.isInteger(v) && v >= lo && v <= hi;

export function cleanScenario(raw) {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) return null;
  if (!isFaction(raw.faction)) return null;
  return {
    faction: raw.faction,
    planet: typeof raw.planet === "string" && planetByName.has(raw.planet) ? raw.planet : null,
    biome: typeof raw.biome === "string" && biomeInfo[raw.biome] ? raw.biome : null,
    hazards: Array.isArray(raw.hazards)
      ? [...new Set(raw.hazards.filter((h) => typeof h === "string" && hazardInfo[h]))]
      : [],
    mission: typeof raw.mission === "string" && missionByName.has(raw.mission) ? raw.mission : null,
    difficulty: inRange(raw.difficulty, 0, 10) ? raw.difficulty : NO_DIFFICULTY,
    squad: inRange(raw.squad, 0, 4) ? raw.squad : NO_SQUAD,
  };
}

/* Two scenarios that say the same thing, compared without caring about
   key order or hazard order. */
export const sameScenario = (a, b) => {
  const key = (x) => (x ? JSON.stringify({ ...x, hazards: [...(x.hazards || [])].sort() }) : "null");
  return key(cleanScenario(a)) === key(cleanScenario(b));
};

export function useScenario() {
  const [scenario, setScenario] = useState(EMPTY_SCENARIO);

  /* Read after mount rather than in the initialiser, the same shape    */
  /* the rest of this app's persistence uses, so nothing touches        */
  /* localStorage during render.                                        */
  useEffect(() => {
    const saved = readSetting(SETTINGS.scenario, FACTION_IDS, null);
    if (isFaction(saved)) setScenario((b) => ({ ...b, faction: saved }));
  }, []);

  useEffect(() => {
    const saved = readDoc(SETTINGS.scenarioEnv);
    if (!saved || typeof saved !== "object") return;
    setScenario((b) => ({
      ...b,
      planet: typeof saved.planet === "string" ? saved.planet : null,
      mission: typeof saved.mission === "string" ? saved.mission : null,
      biome: typeof saved.biome === "string" ? saved.biome : null,
      hazards: Array.isArray(saved.hazards) ? saved.hazards.filter((h) => typeof h === "string") : [],
      difficulty: Number.isInteger(saved.difficulty) && saved.difficulty >= 0 && saved.difficulty <= 10
        ? saved.difficulty
        : NO_DIFFICULTY,
      squad: Number.isInteger(saved.squad) && saved.squad >= 0 && saved.squad <= 4 ? saved.squad : NO_SQUAD,
    }));
  }, []);

  /* A mission belongs to the fronts it appears on. Changing front keeps
     the mission only when the new front has it too; otherwise the scenario
     would go on claiming a Terminid mission on an Automaton planet, which
     is what the curator found on 30 September 2026. */
  const setFaction = useCallback((id) => {
    const next = isFaction(id) ? id : null;
    setScenario((b) => {
      const m = b.mission ? missionByName.get(b.mission) : null;
      const keep = !next || !m || m.factions.includes(next);
      return keep ? { ...b, faction: next } : saveEnv({ ...b, faction: next, mission: null });
    });
    writeSetting(SETTINGS.scenario, next === null ? "" : next);
  }, []);

  const saveEnv = (next) => {
    writeDoc(SETTINGS.scenarioEnv, {
      planet: next.planet,
      biome: next.biome,
      hazards: next.hazards,
      mission: next.mission,
      difficulty: next.difficulty,
      squad: next.squad,
    });
    return next;
  };

  /* Choosing a planet fills the environment. Clearing it leaves the      */
  /* environment alone rather than wiping it, because you may have set    */
  /* biome and hazards by hand and only used the planet to get there.     */
  const setPlanet = useCallback((name) => {
    setScenario((b) => {
      if (!name) return saveEnv({ ...b, planet: null });
      const p = planetByName.get(name);
      if (!p) return b;
      return saveEnv({ ...b, planet: p.name, biome: p.biome || null, hazards: [...(p.hazards || [])] });
    });
  }, []);

  /* Setting either by hand drops the planet, because the scenario would     */
  /* otherwise claim to be somewhere it is not.                           */
  const setBiome = useCallback((slug) => {
    setScenario((b) => saveEnv({ ...b, biome: slug || null, planet: null }));
  }, []);

  const toggleHazard = useCallback((slug) => {
    setScenario((b) => {
      const on = b.hazards.includes(slug);
      return saveEnv({
        ...b,
        hazards: on ? b.hazards.filter((h) => h !== slug) : [...b.hazards, slug],
        planet: null,
      });
    });
  }, []);

  const setMission = useCallback((name) => {
    setScenario((b) => saveEnv({ ...b, mission: missionByName.has(name) ? name : null }));
  }, []);

  /* Difficulty is the sixth answer and the only one that is not about    */
  /* the place. It does not clear with the environment: swapping planet    */
  /* does not mean you have stopped playing at the level you play at.      */
  const setDifficulty = useCallback((level) => {
    const n = Number(level);
    const next = Number.isInteger(n) && n >= 0 && n <= 10 ? n : NO_DIFFICULTY;
    setScenario((b) => saveEnv({ ...b, difficulty: next }));
  }, []);

  const setSquad = useCallback((n) => {
    const v = Number(n);
    const next = Number.isInteger(v) && v >= 0 && v <= 4 ? v : NO_SQUAD;
    setScenario((b) => saveEnv({ ...b, squad: next }));
  }, []);

  const clearEnvironment = useCallback(() => {
    setScenario((b) => saveEnv({ ...b, planet: null, biome: null, hazards: [], mission: null }));
  }, []);

  /* The whole scenario at once, for following a party's host. Cleaned
     first; anything that does not clean leaves the scenario alone. */
  const replaceScenario = useCallback((raw) => {
    const next = cleanScenario(raw);
    if (!next) return;
    writeSetting(SETTINGS.scenario, next.faction);
    setScenario(() => saveEnv(next));
  }, []);

  return { scenario, setFaction, setPlanet, setBiome, toggleHazard, setMission, setDifficulty, setSquad, clearEnvironment, replaceScenario };
}

/* ------------------------------------------------------------------ */
/* Tier list filters                                                   */
/*                                                                     */
/* These used to live inside TierBrowser, which meant they were thrown */
/* away every time you looked at Drop Bay and came back. Setting a tier */
/* floor and a couple of categories is real work and losing it on a    */
/* glance at your builds is the kind of small rudeness that makes a    */
/* tool feel careless.                                                  */
/*                                                                     */
/* Lifted here rather than into useCollectionState because this is not     */
/* collection data. It describes what you are looking at, the same as  */
/* the scenario and the theme, so it stays out of the export for the same */
/* reason those do.                                                     */
/*                                                                     */
/* Per category, because a damage type filter that made sense on       */
/* primaries produces an empty list on boosters. That was already true */
/* and is kept.                                                         */
/* ------------------------------------------------------------------ */

/* Which of the two rating columns the list is ordered by. Defaults to
   ours: the community vote is the reference, but the whole point of the
   second column is that it knows where you are dropping, so that is the
   one worth ranking by until you say otherwise. */
export const SORT_COLUMNS = ["dds", "ugg"];

/* ------------------------------------------------------------------ */
/* The drop planner's answers                                          */
/*                                                                     */
/* The front is not here: it is the scenario's own front, so answering */
/* "against what" is choosing it. These are the rest, which describe   */
/* how you like to play rather than where you are going, so they keep  */
/* from one session to the next. Merged over a blank on read, the same */
/* as the tier filters, so a field added later does not arrive as      */
/* undefined.                                                          */
/* ------------------------------------------------------------------ */

export const BLANK_PLANNER = { kind: null, caves: "any", megacities: "any", avoidHazards: [] };
const CAVES = ["avoid", "any", "only"];
const MEGACITIES = ["fewer", "any", "more"];

export function usePlannerPrefs() {
  const [prefs, setPrefs] = useState(BLANK_PLANNER);

  useEffect(() => {
    const saved = readDoc(SETTINGS.planner);
    if (!saved || typeof saved !== "object") return;
    setPrefs({
      kind: typeof saved.kind === "string" && missionTraits[saved.kind] ? saved.kind : null,
      /* Each is a three way choice since 30 September 2026. The two old
         yes or no answers it replaced are read across once: no caves is
         avoid, fewer megacities is fewer. */
      caves: CAVES.includes(saved.caves) ? saved.caves : saved.avoidCaves === true ? "avoid" : "any",
      megacities: MEGACITIES.includes(saved.megacities) ? saved.megacities : saved.fewerMegacities === true ? "fewer" : "any",
      avoidHazards: Array.isArray(saved.avoidHazards)
        ? saved.avoidHazards.filter((h) => typeof h === "string" && hazardInfo[h])
        : [],
    });
  }, []);

  const patch = useCallback((changes) => {
    setPrefs((prev) => {
      const next = { ...prev, ...changes };
      writeDoc(SETTINGS.planner, next);
      return next;
    });
  }, []);

  return [prefs, patch];
}

export function useTierSort() {
  const [sortBy, setSortBy] = useState("dds");

  useEffect(() => {
    const saved = readSetting(SETTINGS.tierSort, SORT_COLUMNS, null);
    if (saved) setSortBy(saved);
  }, []);

  const choose = useCallback((id) => {
    if (!SORT_COLUMNS.includes(id)) return;
    setSortBy(id);
    writeSetting(SETTINGS.tierSort, id);
  }, []);

  return { sortBy, setSortBy: choose };
}

export function useTierFilters(blank, categoryIds) {
  const fresh = () => Object.fromEntries(categoryIds.map((id) => [id, { ...blank }]));
  const [filters, setFilters] = useState(fresh);

  useEffect(() => {
    const saved = readDoc(SETTINGS.tierFilters);
    if (!saved) return;
    /* Merged over a blank rather than trusted, so a filter added in a   */
    /* later version does not read as undefined against saved state      */
    /* written before it existed.                                        */
    setFilters(
      Object.fromEntries(
        categoryIds.map((id) => [id, { ...blank, ...(saved[id] && typeof saved[id] === "object" ? saved[id] : {}) }])
      )
    );
    /* eslint-disable-next-line react-hooks/exhaustive-deps */
  }, []);

  const patch = useCallback((catId, changes) => {
    setFilters((prev) => {
      const next = { ...prev, [catId]: { ...prev[catId], ...changes } };
      writeDoc(SETTINGS.tierFilters, next);
      return next;
    });
  }, []);

  return { filters, patchFilters: patch };
}
