/**
 * The account endpoints, run inside workerd against a real D1.
 *
 * Ported from Enodia's `worker/auth.test.ts`. **These exist because every bug
 * that backend had was invisible to a green build.** Rate limiting was off and
 * looked on. The client address came from a header a caller can set. A
 * generated schema was missing a NOT NULL column. A type check passed on all
 * three, so the assertions here are about behaviour at the edge of the
 * request: what a stranger gets back, with what headers, after how many tries.
 *
 * **A test here is only kept after it was seen failing** against the broken
 * code. The rate limiting pair were checked on 25 September 2026 by removing
 * `enabled: true` and then `ipAddressHeaders` from `worker/auth.ts`, and the
 * sign up tests are what catches a schema generated by the wrong CLI.
 */

import { SELF, env } from 'cloudflare:test'
import { beforeEach, describe, expect, it } from 'vitest'

const ORIGIN = 'https://dds.stigly-official.workers.dev'

/** Cloudflare sets this on every request and overwrites anything the caller sent. */
const from = (ip: string) => ({ 'cf-connecting-ip': ip })

const post = (path: string, body: unknown, headers: Record<string, string> = {}) =>
  SELF.fetch(`${ORIGIN}${path}`, {
    method: 'POST',
    headers: { 'content-type': 'application/json', origin: ORIGIN, ...headers },
    body: JSON.stringify(body),
  })

/** The cookie a browser would send back, pulled out of a set-cookie. */
const cookieFrom = (response: Response): string =>
  (response.headers.get('set-cookie') ?? '').split(';')[0] ?? ''

let seq = 0
const freshEmail = () => `t${Date.now()}-${seq++}@example.invalid`
const PASSWORD = 'a-long-enough-password-here'

async function signUpFresh(ip = '203.0.113.1') {
  const email = freshEmail()
  const response = await post('/api/auth/sign-up/email', { name: 'Tester', email, password: PASSWORD }, from(ip))
  return { email, response, cookie: cookieFrom(response) }
}

beforeEach(async () => {
  // One database across the file, so the limiter's counters have to be cleared
  // or one test's attempts bleed into the next one's budget.
  await env.DB.prepare('delete from rate_limit').run()
})

describe('what the deployment admits to', () => {
  /**
   * Stage 1 has no mail at all: no domain, so no MAIL_FROM, and no key. The
   * precondition is asserted rather than assumed, so that configuring one half
   * later cannot leave this passing while testing nothing.
   */
  it('reports no password reset while mail is not configured', async () => {
    expect((env as { RESEND_API_KEY?: string }).RESEND_API_KEY ?? '').toBe('')

    const response = await SELF.fetch(`${ORIGIN}/api/capabilities`)
    expect(response.status).toBe(200)
    // The UI warns that a forgotten password cannot be recovered on the
    // strength of this. If it ever lies, somebody is shown a flow that sends
    // nothing.
    expect(await response.json()).toEqual({ passwordReset: false })
  })

  /**
   * public/_headers stops at static files, so the Worker has to say this
   * itself. Checked on better-auth's own answer as well as ours, because that
   * one is built by the library and is the easy one to miss.
   */
  it('sends nosniff and no-store on every API answer, better-auth included', async () => {
    const { response } = await signUpFresh('203.0.113.77')
    for (const answer of [
      await SELF.fetch(`${ORIGIN}/api/capabilities`),
      await SELF.fetch(`${ORIGIN}/api/me`),
      response,
    ]) {
      expect(answer.headers.get('x-content-type-options')).toBe('nosniff')
      expect(answer.headers.get('cache-control')).toContain('no-store')
    }
  })

  it('answers an unknown API path with a 404, not the app', async () => {
    const response = await SELF.fetch(`${ORIGIN}/api/nothing-here`)
    expect(response.status).toBe(404)
    expect(response.headers.get('content-type')).toContain('application/json')
  })
})

describe('the session gate', () => {
  it('refuses a protected route with no session', async () => {
    expect((await SELF.fetch(`${ORIGIN}/api/me`)).status).toBe(401)
  })

  it('refuses a forged cookie rather than trusting it', async () => {
    const response = await SELF.fetch(`${ORIGIN}/api/me`, {
      headers: { cookie: 'better-auth.session_token=not.a.real.signature' },
    })
    expect(response.status).toBe(401)
  })

  /** Also the test that fails first if worker/schema.ts came from the wrong CLI. */
  it('signs up, holds the session, and lets go on sign out', async () => {
    const { response, cookie } = await signUpFresh()
    expect(response.status).toBe(200)
    expect(cookie).toContain('session_token')

    const me = await SELF.fetch(`${ORIGIN}/api/me`, { headers: { cookie } })
    expect(me.status).toBe(200)
    // Only these three leave the server. Nothing about sessions or the
    // password hash, and the id is the account's own.
    expect(Object.keys(((await me.json()) as { user: object }).user).sort()).toEqual(['email', 'id', 'name'])

    expect((await post('/api/auth/sign-out', {}, { cookie })).status).toBe(200)
    expect((await SELF.fetch(`${ORIGIN}/api/me`, { headers: { cookie } })).status).toBe(401)
  })

  it('refuses a session whose row has expired', async () => {
    const { cookie } = await signUpFresh()
    expect((await SELF.fetch(`${ORIGIN}/api/me`, { headers: { cookie } })).status).toBe(200)

    // Backdated in the database rather than by waiting a week. The cookie is
    // still perfectly valid, which is the point: expiry has to be enforced
    // against the row and not against the signature.
    await env.DB.prepare('update session set expires_at = (unixepoch() - 3600) * 1000').run()

    expect((await SELF.fetch(`${ORIGIN}/api/me`, { headers: { cookie } })).status).toBe(401)
  })

  it('sets the session cookie HttpOnly, Secure and SameSite=Lax', async () => {
    const { response } = await signUpFresh()
    const raw = response.headers.get('set-cookie') ?? ''
    // HttpOnly is the one that matters: it stops a script reading the token if
    // anything is ever injected into the page.
    expect(raw).toMatch(/HttpOnly/i)
    expect(raw).toMatch(/Secure/i)
    expect(raw).toMatch(/SameSite=Lax/i)
  })

  /** The password is stored hashed, never as typed. Read straight off the row. */
  it('never stores the password as typed', async () => {
    const { email } = await signUpFresh()
    const row = await env.DB.prepare(
      'select a.password from account a join user u on u.id = a.user_id where u.email = ?',
    )
      .bind(email)
      .first<{ password: string }>()
    expect(row?.password).toBeTruthy()
    expect(row?.password).not.toContain(PASSWORD)
  })
})

describe('refusals', () => {
  it('refuses the wrong password', async () => {
    const { email } = await signUpFresh()
    expect((await post('/api/auth/sign-in/email', { email, password: 'wrong-password-x' })).status).toBe(401)
  })

  it('refuses a second account on the same email', async () => {
    const { email } = await signUpFresh()
    const response = await post('/api/auth/sign-up/email', { name: 'Impostor', email, password: PASSWORD })
    expect(response.status).toBe(422)
  })

  it('refuses a request from another origin', async () => {
    const { email } = await signUpFresh()
    const response = await SELF.fetch(`${ORIGIN}/api/auth/sign-in/email`, {
      method: 'POST',
      headers: { 'content-type': 'application/json', origin: 'https://evil.example' },
      body: JSON.stringify({ email, password: PASSWORD }),
    })
    expect(response.status).toBe(403)
  })
})

/**
 * The regression that matters most. better-auth's rate limiting defaults to
 * `NODE_ENV === 'production'`, which Workers never sets, so the default reads
 * as safe and does nothing here. If somebody deletes the `rateLimit` block from
 * `worker/auth.ts` believing the library covers it, this says otherwise.
 */
describe('rate limiting', () => {
  it('stops brute forcing a password after the configured 20', async () => {
    const { email } = await signUpFresh('198.51.100.10')

    const codes: number[] = []
    for (let attempt = 0; attempt < 24; attempt += 1) {
      const response = await post(
        '/api/auth/sign-in/email',
        { email, password: 'deliberately-wrong' },
        from('198.51.100.10'),
      )
      codes.push(response.status)
    }

    expect(codes).toContain(429)
    // The limit is 20 per 300 seconds, so the first refusal lands on the 21st,
    // off by at most the one sign up above.
    expect(codes.indexOf(429)).toBeGreaterThanOrEqual(19)
    expect(codes.indexOf(429)).toBeLessThanOrEqual(21)
  })

  /**
   * The other half. Cloudflare appends the real address to x-forwarded-for
   * rather than replacing it, so a limiter reading that header could be reset
   * by changing a string.
   */
  it('cannot be reset by changing x-forwarded-for', async () => {
    const { email } = await signUpFresh('198.51.100.20')

    for (let attempt = 0; attempt < 22; attempt += 1) {
      await post('/api/auth/sign-in/email', { email, password: 'deliberately-wrong' }, from('198.51.100.20'))
    }

    const spoofed = await post(
      '/api/auth/sign-in/email',
      { email, password: 'deliberately-wrong' },
      { ...from('198.51.100.20'), 'x-forwarded-for': '9.9.9.9' },
    )
    expect(spoofed.status).toBe(429)
  })

  it('counts each address separately, so one attacker cannot lock everybody out', async () => {
    const { email } = await signUpFresh('198.51.100.30')

    for (let attempt = 0; attempt < 22; attempt += 1) {
      await post('/api/auth/sign-in/email', { email, password: 'deliberately-wrong' }, from('198.51.100.30'))
    }

    // Another address, the right password. A limiter keyed on nothing would be
    // shared, and one bad actor would take sign in down for everybody.
    const elsewhere = await post('/api/auth/sign-in/email', { email, password: PASSWORD }, from('198.51.100.31'))
    expect(elsewhere.status).toBe(200)
  })
})
