import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import App from "./App.jsx";
/* Oswald and JetBrains Mono, served from this origin. Generated by
   scripts/fonts.mjs, which says why they are not linked from Google. */
import "./fonts.css";
import "./index.css";

createRoot(document.getElementById("root")).render(
  <StrictMode>
    <App />
  </StrictMode>
);
